---
- hosts: localhost
  connection: local
  sudo: yes

  vars_files:
    - vars.yml

  tasks:
    - include: tasks/base.yml tags=base
    - include: tasks/network.yml tags=base
#    - include: tasks/samba.yml tags=base
#    - include: tasks/webdev.yml tags=dev
    - include: tasks/ssh.yml tags=base
#    - include: tasks/apps.yml tags=apps
#    - include: tasks/ngrok.yml tags=dev
#    - include: tasks/calibre.yml tags=apps
    - include: tasks/vlc.yml tags=apps
#    - include: tasks/yubikey.yml tags=secops
#    - include: tasks/dropbox.yml tags=apps
#    - include: tasks/scrot.yml tags=apps
    - include: tasks/skype.yml tags=apps
#    - include: tasks/terminator.yml tags=apps
    - include: tasks/fonts.yml tags=fonts
    - include: tasks/zsh.yml tags=zsh
    - include: tasks/bash.yml tags=bash
#    - include: tasks/clojure.yml tags=clojure,lang
#    - include: tasks/chruby.yml tags=ruby,lang
#    - include: tasks/ruby-install.yml tags=ruby,lang
#    - include: tasks/ruby.yml tags=ruby,lang
    - include: tasks/javascript.yml tags=js,lang
#    - include: tasks/phantomjs.yml tags=dev
#    - include: tasks/webkit.yml tags=dev
    - include: tasks/chrome.yml tags=apps
#    - include: tasks/opera.yml tags=apps
#    - include: tasks/tor.yml tags=apps
#    - include: tasks/pass.yml tags=apps
#    - include: tasks/scnsht.yml tags=apps
#    - include: tasks/keepassx.yml tags=apps
    - include: tasks/gnome.yml tags=desktop
#    - include: tasks/numix.yml tags=desktop
#    - include: tasks/i3.yml tags=desktop
#    - include: tasks/neovim.yml tags=dev
#    - include: tasks/spacemacs.yml tags=dev
#    - include: tasks/tmux.yml tags=dev
    - include: tasks/git.yml tags=dev
#    - include: tasks/gitencrypt.yml tags=dev
    - include: tasks/vagrant.yml tags=dev
    - include: tasks/virtualbox.yml tags=dev
#    - include: tasks/boxes.yml tags=dev
#    - include: tasks/docker.yml tags=dev
#    - include: tasks/imagemagick.yml tags=apps
#    - include: tasks/test.yml tags=test
    # - include: tasks/rocketchat.yml tags=chat
#    - include: tasks/databases.yml tags=databases
#    - include: tasks/gpg.yml tags=secops
#    - include: tasks/clamav.yml tags=secops
#    - include: tasks/keybase.yml tags=secops
    - include: tasks/dotfiles.yml tags=dotfiles
#    - include: tasks/hardware.yml tags=drivers
#    - include: tasks/sec.yml tags=apps
#    - include: tasks/fitbit.yml tags=apps
