---
- hosts: localhost
  connection: local

  vars_files:
    - vars.yml

  tasks:
    - import_tasks: tasks/base.yml 
      tags:
        - base
    - import_tasks: tasks/network.yml 
      tags: network
#    - import_tasks: tasks/samba.yml tags=base
#    - import_tasks: tasks/webdev.yml tags=dev
    - import_tasks: tasks/ssh.yml 
      tags: ssh
#    - import_tasks: tasks/apps.yml tags=apps
#    - import_tasks: tasks/ngrok.yml tags=dev
#    - import_tasks: tasks/calibre.yml tags=apps
    - import_tasks: tasks/vlc.yml 
      tags: vlc
#    - import_tasks: tasks/yubikey.yml tags=secops
#    - import_tasks: tasks/dropbox.yml tags=apps
#    - import_tasks: tasks/scrot.yml tags=apps
#    - import_tasks: tasks/skype.yml tags=apps
#    - import_tasks: tasks/terminator.yml tags=apps
    - import_tasks: tasks/fonts.yml 
      tags: fonts
    - import_tasks: tasks/zsh.yml 
      tags: zsh
    - import_tasks: tasks/bash.yml 
      tags: bash
    - import_tasks: tasks/python.yml
      tags: python
#    - import_tasks: tasks/clojure.yml tags=clojure,lang
#    - import_tasks: tasks/chruby.yml tags=ruby,lang
#    - import_tasks: tasks/ruby-install.yml tags=ruby,lang
#    - import_tasks: tasks/ruby.yml tags=ruby,lang
    - import_tasks: tasks/java.yml 
      tags:
        - java
    - import_tasks: tasks/android.yml
      tags: android
    - import_tasks: tasks/javascript.yml 
      tags: javascript
    - import_tasks: tasks/node.yml
      tags: node
#    - import_tasks: tasks/phantomjs.yml tags=dev
#    - import_tasks: tasks/webkit.yml tags=dev
    - import_tasks: tasks/browsers.yml 
      tags: browsers
    - import_tasks: tasks/aws.yml
      tags: python,aws
#    - import_tasks: tasks/opera.yml tags=apps
#    - import_tasks: tasks/tor.yml tags=apps
#    - import_tasks: tasks/pass.yml tags=apps
#    - import_tasks: tasks/scnsht.yml tags=apps
#    - import_tasks: tasks/keepassx.yml tags=apps
#    - import_tasks: tasks/gnome.yml tags=desktop
#    - import_tasks: tasks/numix.yml tags=desktop
#    - import_tasks: tasks/i3.yml tags=desktop
    # - import_tasks: tasks/neovim.yml 
    #   tags:
    #     - dev
    - import_tasks: tasks/sublimetext.yml 
      tags: sublimetext
#    - import_tasks: tasks/spacemacs.yml tags=dev
#    - import_tasks: tasks/tmux.yml tags=dev
    - import_tasks: tasks/git.yml 
      tags: git
#    - import_tasks: tasks/gitencrypt.yml tags=dev
    - import_tasks: tasks/vagrant.yml 
      tags: vagrant
    - import_tasks: tasks/virtualbox.yml 
      tags: virtualbox
    - import_tasks: tasks/heroku.yml
      tags: heroku
#    - import_tasks: tasks/boxes.yml tags=dev
    #- import_tasks: tasks/docker.yml 
    #  tags: docker
#    - import_tasks: tasks/imagemagick.yml tags=apps
#    - import_tasks: tasks/test.yml tags=test
#    - import_tasks: tasks/rocketchat.yml
#    - import_tasks: tasks/databases.yml tags=databases
    - import_tasks: tasks/mongodb.yml
      tags: mongodb
#    - import_tasks: tasks/gpg.yml tags=secops
#    - import_tasks: tasks/clamav.yml tags=secops
#    - import_tasks: tasks/keybase.yml tags=secops
    # - import_tasks: tasks/dotfiles.yml 
    #   tags:
    #     - dotfiles
#    - import_tasks: tasks/hardware.yml tags=drivers
#    - import_tasks: tasks/sec.yml tags=apps
#    - import_tasks: tasks/fitbit.yml tags=apps
    - import_tasks: tasks/slack.yml 
      tags: slack
    - import_tasks: tasks/display_home.yml
      tags: display
    - import_tasks: tasks/flux.yml
      tags: flux
