---
- name: Add Google PPA key
  sudo: true
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

- name: Add Google PPA
  apt_repository: repo="deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" state=present
  sudo: true

- name: Install Chrome stable
  sudo: true
  apt: name=google-chrome-stable state=installed

- name: Install latest chromium package with codecs
  apt: pkg="{{ item }}" state=present force=yes
  with_items:
    - chromium-browser
    - chromium-browser-l10n
    - chromium-codecs-ffmpeg-extra
