---
# Install & Configure Display Settings

- name: Setting up dual displays
  copy:
    src: files/display_home/monitors.xml
    dest: /home/{{user}}/.config/monitors.xml

- name: Add PPA for NVIDIA
  become: yes
  apt_repository: 
    repo: ppa:graphics-drivers
    codename: xenial
    state: present

- name: Installing NVIDIA drivers
  become: yes
  apt: 
    name: nvidia-384
    state: installed