---
# Install & Configure Display Settings

- name: Setting up dual displays
  sudo: false
  copy:
    src: files/display_home/monitors.xml
    dest: /home/{{user}}/.config/monitors.xml

- name: Add PPA for NVIDIA
  sudo: true
  apt_repository: 
    repo: ppa:graphics-drivers
    state: present

- name: Installing NVIDIA drivers
  apt: 
    name: nvidia-384
    state: installed