- name: download heroku CLI
  sudo: false
  get_url:
    url: https://cli-assets.heroku.com/install-ubuntu.sh
    dest: /tmp/heroku-install.sh
    mode: 0550

- name: install heroku CLI
  shell: /tmp/heroku-install.sh