---
# https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/
- block:
  - name: Import MongoDB public GPG Key
    apt_key:
        keyserver: keyserver.ubuntu.com
        id: 0C49F3730359A14518585931BC711F9BA15703C6
  - name: Add MongoDB repository into sources list
    apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse
        codename: xenial
        state: present
  - name: Install MongoDB package
    apt:
        name: mongodb-org
        update_cache: yes
  become: yes