# Install and configure slack
---
- name: Check if slack is installed
  command: dpkg-query -W slack-desktop
  register: slack_check_deb
  failed_when: slack_check_deb.rc > 1
  changed_when: slack_check_deb.rc == 1

- name: Download slack
  get_url: 
    url="{{ slack_url }}"
    dest="/home/{{user}}/Downloads/slack.deb"
  when: slack_check_deb.rc == 1

- name: Install slack
  become: yes
  apt: deb="/home/{{user}}/Downloads/slack.deb"
  when: slack_check_deb.rc == 1