# Install and configure sublime text
---
- name: install sublimetext gpg key
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg

- name: installing sublimetext repository
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    state: present

- name: installing sublimetext
  apt:
    pkg: sublime-text
    state: installed

- name: create sublimetext preferences directory
  sudo: false
  file:
    path: /home/{{user}}/.config/sublime-text-3/Packages/User/
    state: directory
    mode: 0755

- name: copying sublimetext preferences
  copy:
    src: files/sublimetext/Preferences.sublime-settings
    dest: /home/{{user}}/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
