---
# Install Virtualbox

- name: Add apt package source
  sudo: true
  apt: 
    deb: http://download.virtualbox.org/virtualbox/5.1.26/virtualbox-5.1_5.1.26-117224~Ubuntu~xenial_amd64.deb 
    state: installed

# https://forums.virtualbox.org/viewtopic.php?f=7&t=77363&start=15
