---
- name: install zsh
  become: yes
  apt: pkg=zsh state=installed

- name: Set ZSH as default shell
  become: yes
  command: chsh -s /bin/zsh {{ user }}

- name: Install Oh my ZSH
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git
       dest=/home/{{user}}/.oh-my-zsh
       accept_hostkey=yes

- name: Copy zshrc
  template: src=templates/zshrc dest=/home/{{user}}/.zshrc force=yes

- name: Copy .zshrc.local (once)
  copy: src=templates/zshrc.local dest=/home/{{user}}/.zshrc.local force=no

# - name: download Oh my ZSH
#   sudo: false
#   get_url:
#     url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
#     dest: /tmp/ohmyzsh-install.sh
#     mode: 0550

# - name: install oh-my-sh
#   sudo: false
#   shell: /tmp/ohmyzsh-install.sh